name: Trigger auto deployment for aca20150217

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca20150217-AutoDeployTrigger-3c5e5839-3bcd-44fb-b6f2-c568a5492e35.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACA20150217_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACA20150217_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACA20150217_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 20250214acr.azurecr.io
          registryUsername: ${{ secrets.ACA20150217_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACA20150217_REGISTRY_PASSWORD }}
          containerAppName: aca20150217
          resourceGroup: demo20150217-rg
          imageToBuild: 20250214acr.azurecr.io/aca20150217:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


